"""Render the experiment database to EXPERIMENTS.md — the running record.

Every run, including the failures, lands here. The failures are the more useful
half: they are what stops the same dead end being explored twice.
"""
import os, sqlite3
import pandas as pd
import benchmark as B

def main():
    df = B.table()
    if df.empty:
        print("no experiments logged yet"); return
    df = df.drop_duplicates(subset=["name", "split"], keep="last")
    beat = df[df.alpha_total_pct > 0].sort_values("alpha_total_pct", ascending=False)
    lost = df[df.alpha_total_pct <= 0].sort_values("alpha_total_pct", ascending=False)

    def rows(d):
        out = []
        for _, r in d.iterrows():
            out.append(
                f"| {r['name']} | {r['split']} | {0 if r['trades'] != r['trades'] else int(r['trades'])} | "
                f"{r['cost_drag']:.1f}% | {r['total_pct']:+.1f}% | {r['cagr']:+.1f}% | "
                f"{r['bench_cagr']:+.1f}% | {r['alpha_total_pct']:+.1f}% | "
                f"{r['sharpe']:.2f} | {r['max_dd']:.1f}% |")
        return "\n".join(out)

    hdr = ("| experiment | split | trades | cost drag | total | CAGR | benchmark CAGR "
           "| alpha | Sharpe | maxDD |\n|---|---|---|---|---|---|---|---|---|---|")
    md = f"""# Experiment log

Every strategy scored on the frozen harness in `benchmark.py`. Nothing in that
harness is tuned: the split dates, the real Groww cost model, the capital
(Rs {B.CAPITAL:,.0f}) and the benchmark are constants, so numbers here are comparable
across experiments and across time.

- **TRAIN** {B.TRAIN[0]} .. {B.TRAIN[1]} — for forming hypotheses and choosing parameters.
- **TEST** {B.TEST[0]} .. {B.TEST[1]} — touched only to confirm a finished hypothesis.
  A result quoted on TRAIN is a hypothesis; only TEST is a result.
- **Benchmark**: equal-weight buy & hold of the same universe over the same window,
  paying entry cost once. Beating zero is not the bar; beating this is.
- **alpha** = strategy total return minus benchmark total return over the window.

`cost drag` is total trading cost as a percentage of starting capital — the single
most informative column in this table, and the one that killed most experiments.

## Beat the benchmark ({len(beat)})

{hdr}
{rows(beat)}

## Lost to the benchmark ({len(lost)})

{hdr}
{rows(lost)}

## Standing conclusions

1. **Turnover is the dominant cost term.** The same signal at trail=4%/hold=20
   versus trail=None/hold=120 goes from 17.5% cost drag to 1.6%. Every
   high-turnover variant tested has lost to simply holding the universe.
2. **The Scanner's Buy % has no predictive power** (rank-IC -0.004, t=-0.20;
   bottom-5 beat top-5; both lose to random). Do not build on it.
3. **Trailing stops reduce net return at every width tested**, on daily bars and
   on 15-minute bars alike. What they buy is tail protection, not return.
4. **Small accounts are structurally disadvantaged.** A flat Rs 13.5 DP charge is
   1.35% of a Rs 1,000 ticket. Below ~Rs 50,000 total capital, do not run more
   than 3 positions.

*Generated by `exp_report.py` from `cache/experiments.sqlite`.*
"""
    open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "EXPERIMENTS.md"), "w").write(md)
    print(f"wrote EXPERIMENTS.md — {len(df)} experiments ({len(beat)} beat the benchmark)")

if __name__ == "__main__":
    main()
