# NSE universe (Nifty 100 + liquid midcaps). Edit freely.
SYMBOLS = """RELIANCE TCS HDFCBANK ICICIBANK INFY HINDUNILVR ITC SBIN BHARTIARTL KOTAKBANK
LT AXISBANK ASIANPAINT MARUTI SUNPHARMA TITAN ULTRACEMCO BAJFINANCE NESTLEIND WIPRO
ONGC NTPC POWERGRID M&M TATASTEEL JSWSTEEL ADANIENT ADANIPORTS COALINDIA
HCLTECH TECHM INDUSINDBK BAJAJFINSV HDFCLIFE SBILIFE GRASIM BRITANNIA CIPLA DRREDDY
DIVISLAB EICHERMOT HEROMOTOCO BAJAJ-AUTO APOLLOHOSP HINDALCO VEDL BPCL IOC GAIL
TATAPOWER TATACONSUM DABUR GODREJCP MARICO COLPAL BERGEPAINT PIDILITIND SIEMENS ABB
HAVELLS DLF LODHA GODREJPROP AMBUJACEM SHREECEM ACC BANKBARODA PNB CANBK
UNIONBANK IDFCFIRSTB FEDERALBNK AUBANK CHOLAFIN SHRIRAMFIN MUTHOOTFIN LICHSGFIN RECLTD
PFC IRFC PAYTM NYKAA POLICYBZR DMART TRENT PAGEIND
UBL VBL JUBLFOOD NAUKRI INDIGO ADANIGREEN ADANIPOWER JINDALSTEL SAIL NMDC
PERSISTENT COFORGE MPHASIS OFSS BOSCHLTD MOTHERSON BHARATFORG CUMMINSIND ASHOKLEY
TVSMOTOR BEL HAL BHEL IRCTC CONCOR LUPIN AUROPHARMA TORNTPHARM ALKEM
ZYDUSLIFE BIOCON MAXHEALTH FORTIS SRF UPL PIIND DEEPAKNTR TATACHEM
""".split()
TICKERS = [s + ".NS" for s in SYMBOLS]
